### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by gamer4eg** [ElvUI-MoP/ElvUI-5.4.8#26]
Unlike the version from Curse, your version has problems with performance ...
Ready to test if you want, the added functionality is very convenient!
But lagging.
At the start of combat with raidboss, FPS falls very much and gradually begins to grow.

And I apologize for Google translator.

**Comment by Apollyonn** [comment]
I need more info. Do you use any plugins? Does this happen only at boss fights? Does this happend with only elvui enabled? Did you had same issues with older versions of this addon?

**Comment by Maczuga** [comment]
I can pretty much relate to that:
- No ElvUI plugins used
- Happens mostly on raids for me (I was doing ToES 10 HC)
- Other addons were present, but this is tied to this fork of ElvUI - I was using version at least 1 month old from now.

Game showed me that I have ~80 fps - but it felt like 20 max.
Can't remember now whether /reloadui helped.
Since I switched to curse version this problem is gone.

If you need some profiling let me know what do you need and point some tips what needs to be done.

**Comment by Apollyonn** [comment]
Unfortunatly i can't test it myself right now because i don't have any raiding toons. If this happens only during boss fights then i suspect the problem is somewhere in the unitframes.
If you have the time please get the latest version and test it. If the problem is still there then disable the unitframes module and test it again.

**Comment by Maczuga** [comment]
Alright, today is the reset day so I'll try to test it at least on LFR.

BTW. it was not only during boss fights. FPS drop persisted even between boss fights.

**Comment by Maczuga** [comment]
Issue persists, had same thing on ToES LFR today. I couldn't disable unitframes because I was in combat while it came to my mind. Gonna try without frames tommorow.

**Comment by Maczuga** [comment]
Not unit frames related. With and without 90 fps +, but feels like 30 or less.

**Comment by Maczuga** [comment]
It's really hard to track down. I have even disabled everything - it won't reset until I close Wow and relaunch.

**Comment by Maczuga** [comment]
More info on that - so far it ONLY occurs on ToES - I have no issues when doing world content, MSV or HoF. And it only goes down by some % after every wipe. Keep in mind, that it shows that my FPS is over 100, but it feels really like 20.

**Comment by damnee** [comment]
Elvui nameplates are the cause of this problem.

**Comment by Apollyonn** [comment]
Several things has been updated since this was opened, i have no clue if its fixed or not since i never encountered this issue. If you still have issues re open this.
